// max 8 layers
#define LAYER_STATE_UBIT

#define TAPPING_TERM 250
#define TAPPING_TOGGLE 3
#define IGNORE_MOD_TAP_INTERRUPT

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
// #define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE
